# Generated by Django 4.1 on 2022-09-30 07:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_name', models.CharField(max_length=250, unique=True)),
                ('apartment_type', models.CharField(choices=[('Flats', 'Flats'), ('Bungalow', 'Bungalow'), ('Mansionaite', 'Mansionaite')], max_length=100)),
                ('apartment_description', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('town_located', models.CharField(max_length=50)),
                ('apartment_location', models.CharField(max_length=50)),
                ('management_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.IntegerField()),
                ('monthly_rent', models.PositiveIntegerField(default=0)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house_type', models.CharField(choices=[('Bedsitter', 'Bedsitter'), ('1 Bedroom', '1 Bedroom'), ('2 Bedroom', '2 Bedroom'), ('3 Bedroom', '3 Bedroom')], max_length=100)),
                ('descption', models.CharField(blank=True, max_length=250, null=True)),
                ('occupancy', models.CharField(choices=[('Occupied', 'Occupied'), ('Vacant', 'Vacant')], default='Vacant', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rental_houses.apartment')),
            ],
            options={
                'verbose_name': 'Houses',
                'verbose_name_plural': 'Houses',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(choices=[('JAN', 'JAN'), ('FEB', 'FEB'), ('MARCH', 'MARCH'), ('APRL', 'APRL'), ('JUN', 'JUN'), ('JULY', 'JULY'), ('AUG', 'AUG'), ('SEPT', 'SEPT'), ('OCT', 'OCT'), ('NOV', 'NOV'), ('DEC', 'DEC')], max_length=20)),
                ('rent', models.PositiveIntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], default='unpaid', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rental_houses.apartment')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rental_houses.houses')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('Id_number', models.IntegerField()),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-f_name',),
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=150)),
                ('national_Id', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('physical_Adress', models.CharField(max_length=100)),
                ('Occupation', models.CharField(max_length=150)),
                ('emergency_person_name', models.CharField(max_length=250)),
                ('emergency_person_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_rent', models.PositiveIntegerField(default=0)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('payment', models.PositiveIntegerField(default=0)),
                ('over_payment', models.PositiveIntegerField(default=0)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('payment_mode', models.CharField(choices=[('Mpesa', 'Mpesa'), ('Cash', 'Cash'), ('Bank', 'Bank')], default='Cash', max_length=50)),
                ('reference_no', models.CharField(blank=True, max_length=50, null=True)),
                ('management_earning', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rental_houses.apartment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rental_houses.invoice')),
            ],
            options={
                'ordering': ('-invoice',),
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rental_houses.tenant'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rental_houses.landlord'),
        ),
        migrations.CreateModel(
            name='Allocate_House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rental_houses.apartment')),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Rental_houses.houses')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rental_houses.tenant')),
            ],
        ),
    ]
