# Generated by Django 4.1 on 2022-09-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental_houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='monthly_rent',
            field=models.PositiveIntegerField(),
        ),
    ]
