# Generated by Django 4.1 on 2022-09-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rental_houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earning', models.PositiveIntegerField(default=0)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('management_total_earning', models.PositiveIntegerField(default=0)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rental_houses.apartment')),
                ('paid_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rental_houses.invoice_payment')),
            ],
        ),
    ]
