# Generated by Django 4.1 on 2022-09-07 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rental_houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='Id_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_name', models.CharField(max_length=250)),
                ('apartment_type', models.CharField(choices=[('1-2 Bedroom Apartment', '1-2 Bedroom Apartment'), ('2-3 Bedroom Apartment', '2-3 Bedroom Apartment'), ('More than 3 bedroom', 'More than 3 bedroom')], max_length=100)),
                ('apartment_description', models.TextField()),
                ('town_located', models.CharField(max_length=50)),
                ('apartment_location', models.CharField(max_length=50)),
                ('management_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('apartment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rental_houses.landlord')),
            ],
        ),
    ]
