# Generated by Django 4.1 on 2022-09-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental_houses', '0002_alter_apartment_apartment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='house_type',
            field=models.CharField(choices=[('Bedsitter', 'Bedsitter'), ('1 Bedroom', '1 Bedroom'), ('2 Bedroom', '2 Bedroom'), ('3 Bedroom', '3 Bedroom')], max_length=100),
        ),
    ]
