# Generated by Django 4.1 on 2022-09-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental_houses', '0002_total_earning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_earning',
            name='total_earning',
            field=models.CharField(max_length=100),
        ),
    ]
