# Generated by Django 4.1 on 2022-09-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental_houses', '0003_alter_total_earning_total_earning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_earning',
            name='total_earning',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
