# Generated by Django 4.1 on 2022-09-10 11:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Rental_houses', '0003_houses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=150)),
                ('national_Id', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('physical_Adress', models.CharField(max_length=100)),
                ('Occupation', models.CharField(max_length=150)),
                ('emergency_person_name', models.CharField(max_length=250)),
                ('emergency_person_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
