# Generated by Django 4.1 on 2022-09-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rental_houses', '0004_alter_total_earning_total_earning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-tenant',)},
        ),
        migrations.AlterModelOptions(
            name='invoice_payment',
            options={'ordering': ('-invoice',)},
        ),
        migrations.AlterModelOptions(
            name='landlord',
            options={'ordering': ('-f_name',)},
        ),
        migrations.DeleteModel(
            name='Total_earning',
        ),
    ]
