# Generated by Django 4.1 on 2022-09-29 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rental_houses', '0005_alter_invoice_options_alter_invoice_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterField(
            model_name='allocate_house',
            name='house',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rental_houses.houses'),
        ),
    ]
