# Generated by Django 4.1 on 2022-09-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rental_houses', '0005_allocate_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(choices=[('JAN', 'JAN'), ('FEB', 'FEB'), ('MARCH', 'MARCH'), ('APRL', 'APRL'), ('JUN', 'JUN'), ('JULY', 'JULY'), ('AUG', 'AUG'), ('SEPT', 'SEPT'), ('OCT', 'OCT'), ('NOV', 'NOV'), ('DEC', 'DEC')], max_length=20)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rental_houses.apartment')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rental_houses.houses')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rental_houses.tenant')),
            ],
        ),
    ]
