# Generated by Django 4.1 on 2022-09-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental_houses', '0006_apartment_image_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='rent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
