# Generated by Django 4.1 on 2022-09-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rental_houses', '0007_alter_invoice_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid')], default='unpaid', max_length=50),
        ),
    ]
