from django.urls import path
from Rental_houses import views

urlpatterns = [
    path('',views.index,name='home'),
    path('login_user/',views.login_user,name='login'),
    path('register_user/',views.register_user,name='register_user'),
    path('logout_user/',views.logout_user,name='logout_user'),
    path('landlord/',views.landlord,name='landlord'),
    path('apartments/',views.apartment,name='apartments'),
    path('houses/',views.house,name='houses'),
    path('tenants/',views.tenant,name='tenants'),
    path('lanlords/',views.landlords,name='landlords'),
    path('add_houses/',views.add_houses,name='addhouses'),
    path('update_house/<int:pk>',views.update_house,name='updatehouse'),
    path('update_apartment/<int:pk>',views.update_apartment,name='updateapartment'),
    path('update_landlord/<int:pk>',views.update_landlord,name='updatelandlord'),
    path('delete_landlord/<int:pk>',views.delete_landlord,name='deletelandlord'),
    path('delete_house/<int:pk>',views.delete_house,name='deletehouse'),
    path('assignhouses/<int:id>',views.assignhouses,name='assignhouses'),
    #path('allocate_house/<int:id>',views.allocate_house,name='allocate_house'),
    path('apartmentlist/',views.apartmentlist,name='apartmentlist'),
    path('tenantlist/',views.tenantlist,name='tenantlist'),
    path('vacanthouses/',views.vacanthouses,name='vacanthouses'),
    path('occupiedhouses/',views.occupiedhouses,name='occupiedhouses'),
    path('tenant_details/<int:id>',views.tenant_details,name='tenant_details'),
    path('create_invoice/',views.create_invoice,name='createinvoice'),
    path('generate_invoice/<int:pk>',views.generate_invoice,name='generateinvoice'),
    path('invoices_list/',views.invoices_list,name='invoiceslist'),
    path('invoice_view/<int:pk>',views.invoice_view,name='invoiceview'),
    path('pay_invoice/<int:pk>',views.pay_invoice,name='payinvoice'),
    path('total_rent/',views.total_rent,name='totalrent'),
    path('delete_invoice/<int:pk>',views.delete_invoice,name='deleteinvoice'),
    path('vacate_tenant/<int:pk>',views.vacate_tenant,name='vacatetenant'),
]